# Prettier Config File
tabWidth: 2
proseWrap: 'always'
requirePragma: false
insertPragma: false
embeddedLanguageFormatting: 'auto'
endOfLine: 'auto'
singleQuote: true
jsxSingleQuote: true
useTabs: false
semi: false
trailingComma: 'none'
experimentalTernaries: true
singleAttributePerLine: false
htmlWhitespaceSensitivity: 'css'
arrowParens: 'avoid'
bracketSpacing: true
quoteProps: 'as-needed'
bracketSameLine: false
printWidth: 80
